# Site settings
title: "Bayesian Methods Research Group"
email: bayesml@gmail.com
url: "bayesgroup.github.io"
github_username:  bayesgroup

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  tables: true 
