# Site settings
title: "Courses of Bayesian Methods Research Group"
email: bayesml@gmail.com
url: "bayesgroup.github.io"
github_username:  bayesgroup

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge